repos:
  - repo: local
    hooks:
      - id: format
        name: Format code with Black
        entry: poetry run black .
        language: system
        types: [python]
        pass_filenames: false
      - id: lint
        name: Lint code with Flake8
        entry: poetry run flake8 src tests
        language: system
        types: [python]
        always_run: true
      - id: test-and-coverage
        name: Run tests and check coverage
        entry: poetry run python scripts/precommit_test_and_coverage.py
        language: system
        types: [python]
        always_run: true
